### ISSUE TITLE
project.yaml can use URI scheme for job expressions

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/engine#14]
in a `project.yaml`, users should be able to specify [URI](https://man7.org/linux/man-pages/man7/uri.7.html) paths to job expressions, rather than expressions as stings:
```yaml
jobs:
  job-1:
    expression: "alterState(state => ({ ...state, changed: true }))"
    trigger: trigger-1
  job-2:
    expression: file:///home/taylor/cool-job.js
    trigger: trigger-1
  job-3:
    expression: github:openfn/sample/myJob.js
    trigger: trigger-1
  job-4:
    expression: http://www.github.com/openfn/sample2.js
    trigger: trigger-1
  job-5:
    expression: ./something-relative.js
    trigger: trigger-1
```
we should start with standard URIs, but maybe include some of the above.
